# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/instantnoodlep/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),instantnoodlep)

$(call add-radio-file-sha1-checked,radio/abl.img,e65e284c1d732361e24ea49ae00a179fabc3d878)
$(call add-radio-file-sha1-checked,radio/aop.img,d274d10bbd39c7079522b5399d59526aa6c8809a)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,a1e2c0bfc18eaee981b1659e04e01c07c585982a)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,a5c8f2def2e88fefb447743e99489325f9633f25)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,38c6bd5bf8236790d4107f8c22933206978971d1)
$(call add-radio-file-sha1-checked,radio/devcfg.img,f39463da27b48cee17ec599a93fe31781ddfecb7)
$(call add-radio-file-sha1-checked,radio/dsp.img,bb83cade26d37058e1c64ec7bc14fef6384efcb7)
$(call add-radio-file-sha1-checked,radio/featenabler.img,b72ff4226ae44fecaf5cbb746bbb6cf02c3d93a8)
$(call add-radio-file-sha1-checked,radio/hyp.img,178f8831359203daa05a3042501f368ee50c7fc0)
$(call add-radio-file-sha1-checked,radio/imagefv.img,cc5cc0c621b5bce55a924f521a309d58752f5164)
$(call add-radio-file-sha1-checked,radio/keymaster.img,5bfb4f35216ff897fb7abf4bfbd59206d4033994)
$(call add-radio-file-sha1-checked,radio/logo.img,ed69fe2bcfd0c59a31afc94439d7877ba782ea30)
$(call add-radio-file-sha1-checked,radio/modem.img,390860bbdd75946972ebf2fcfc6ff880520c6991)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,45f674c7722abdaadb2abc4eee241d584e03d0b1)
$(call add-radio-file-sha1-checked,radio/qupfw.img,b5122cdcf1cc157da1030da8c86b298225fa563b)
$(call add-radio-file-sha1-checked,radio/storsec.img,1da418ce8a918d46474f14c1087e00d1e1c31610)
$(call add-radio-file-sha1-checked,radio/tz.img,384537e1d0e4556094e8e1bf266f6f587b6781c1)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,fa2770e52bb3b57b5f0b8912a9f2b78d5a0759c8)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,2853f44630ac3c3befe3492ac1209f89abfbc4d2)
$(call add-radio-file-sha1-checked,radio/xbl.img,374a884f5ee511327bca7eabbdc991dc8448aa5a)

endif
